### ISSUE TITLE
Save user's e-mail when she publish an app

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/civicstack#20]
## Tasks
- [x] Make the _Contact_ field required.
- Create an email field in the users collection and:
  - [x] at signup, extract the e-mail from the GitHub API payload and save it in the email field;
  - [x] run a data migration which parses the existing raw data, extract the e-mail and put it in the email field.

**Comment by jfresco** [comment]
Currently, we are collecting e-mail information from two sources:
1. **Applications**. When somebody uploads an app, there is a _Contact_ field, which is optional. Currently 50 of 87 apps don't have a value in this field.
2. **Log in information**. When a user signs up using GitHub, the API returns lot of user information including the e-mail. The data is in a JSON string, meaning that we need to parse it in order to extract the e-mail. Twitter API doesn't provide this data.

Considering this scenario, I propose two tasks to do here:
1. Make the _Contact_ field required.
2. Create an `email` field in the `users` collection and:
   1. at signup, extract the e-mail from the GitHub API payload and save it in the `email` field;
   2. run a data migration which parses the existing raw data, extract the e-mail and put it in the `email` field.

Thoughts? @mjlescano @gvilarino @Annagramma

**Comment by mjlescano** [comment]
LGTM
