### ISSUE TITLE
Add Disqus or other comments widget

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/civicstack#8]
Disqus login to participate. I think the app's login cannot be reused, so the user will have to do two logins in order to use all app's features.
# Tasks
- [x] Do some research and try to find other widget with better integration features
- [x] Add Disqus widget
- [x] Enable SSO
- [x] Integrate GitHub login
- [x] Integrate Twitter login
- [x] Propagate user attributes, like avatar
- [x] Logout

**Comment by jfresco** [comment]
https://help.disqus.com/customer/portal/articles/236206-integrating-single-sign-on

**Comment by gvilarino** [comment]
If we're SSO'ing this, then I'm all for this. 2 different accounts seem weird tho.
