### ISSUE TITLE
Add optional embedded video as cover

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/civicstack#9]
In each app description.
# Tasks
- [x] Add `video` field in database and API
- [x] Add `video` field in add/edit forms
- [x] Add video placeholder in `app-detail-view`
- [x] Add URL converter (pasting `?v=1234` should be converted to `/embed/1234`)
- [ ] Add video preview in add/edit forms
